version: '3.8'

services:

  elastic:
    build:
      context: configuration/elastic/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./configuration/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      #- elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      discovery.type: single-node
    networks:
      - log-reader

  logstash:
    build:
      context: configuration/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./configuration/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./configuration/logstash/pipeline:/usr/share/logstash/pipeline:ro,z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - log-reader
    depends_on:
      - elastic

  mysql:
    image: mysql:5.7.22
    container_name: mysql-slow-logs
    restart: unless-stopped
    tty: true
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    volumes:
      - ./configuration/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./configuration/mysql/slow-query.sql:/usr/sql/slow-query.sql:ro
      - ./configuration/mysql/test_db:/usr/sql/test_db
      - mysql-logs:/var/log/mysql/
    networks:
      - log-reader

  kibana:
    build:
      context: configuration/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./configuration/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - log-reader
    depends_on:
      - elastic

  filebeat:
    build:
      context: configuration/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
      - type: bind
        source: ./configuration/filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - ./configuration/filebeat/config/mysql.yml:/usr/share/filebeat/modules.d/mysql.yml
      - mysql-logs:/var/log/mysql/
    networks:
      - log-reader
    depends_on:
      - elastic
      - logstash

  mongo:
    image: "mongo:4.1"
    restart: always
    networks:
      - log-reader

  graylog:
    image: graylog/graylog:4.0
    restart: always
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9201/
      - GRAYLOG_HTTP_ENABLE_CORS=true
      - GRAYLOG_ELASTICSEARCH_VERSION=7
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elastic:admin@elasticsearch:9200
    links:
      - mongo:mongo
      - elastic:elastic
    depends_on:
      - mongo
      - elastic
    ports:
      # HTTP
      - 9201:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - log-reader


networks:
  log-reader:
    driver: bridge

volumes:
  mysql-logs:
    driver: local